Database Systems/term-project-itudb2140/interaktivt/routes/auth.py
from flask import Blueprint
from flask import render_template
from flask import redirect
from flask import url_for
from flask import request
from flask import flash
from flask_login import login_user, login_required, logout_user
from werkzeug.security import generate_password_hash, check_password_hash
from ..repository.UserRepository import UserRepository
from ..repository.Database import Database

auth = Blueprint('auth', __name__)


@auth.route('/login')
def login():
    return render_template('login.html')


@auth.route('/login', methods=['POST'])
def login_post():
    # login code goes here
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = UserRepository.fetch_user(email=email)

    # check if the user actually exists
    # take the user-supplied password, hash it, and compare it to the hashed password in the database
    if not user or not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login'))  # if the user doesn't exist or password is wrong, reload the page

    # if the above check passes, then we know the user has the right credentials
    login_user(user, remember=remember)
    return redirect(url_for('main.profile'))


@auth.route('/signup')
def signup():
    return render_template('signup.html')


@auth.route('/signup', methods=['POST'])
def signup_post():
    email = request.form.get('email')
    username = request.form.get('username')
    password = request.form.get('password')

    user = UserRepository.fetch_user(email=email)

    # A user with identical email already exists, redirect back to signup page for retry
    if user:
        flash('Email address already exists')
        return redirect(url_for('auth.signup'))

    # creating new user
    result = UserRepository.insert_user(email=email, username=username,
                                        password=generate_password_hash(password, method='sha256'))
    if result:
        return redirect(url_for('auth.login'))

    return redirect(url_for('auth.signup'))


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

Database Systems/term-project-itudb2140/interaktivt/routes/crud.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user
from flask import request, json
from flask import flash
from ..repository import CountryRepository, HdiRepository, HistoricalRepository
from flask import redirect
from flask import url_for

crud = Blueprint('crud', __name__)


@crud.route('/crud')
def operations():
    return render_template('crud.html')


@crud.route('/add_country', methods=['POST'])
@login_required
def add_country():
    print(request.data)
    if request.get_json():  # None or json
        json_data = request.get_json(silent=True)
        # print(json_data)
        name = json_data['name']
        hdi_rank = json_data['hdi_rank']
        result = CountryRepository.insert_country(name, hdi_rank)
        if result:
            redirect(url_for('main.countries'))
            return json.dumps({'success': True}), 200, {'ContentType': 'application/json'}

        flash('Something went wrong.')
        redirect(url_for('crud.operations'))
        return json.dumps({'success': False}), 500, {'ContentType': 'application/json'}

    else:
        name = request.form.get('name')
        hdi_rank = request.form.get('hdi_rank')

        result = CountryRepository.insert_country(name, hdi_rank)
        if result:
            return redirect(url_for('main.countries'))

        flash('Something went wrong.')
        return redirect(url_for('crud.operations'))


@crud.route('/delete_country', methods=['POST'])
@login_required
def delete_country():
    name = request.form.get('name')

    result = CountryRepository.delete_country(name)
    if result:
        return redirect(url_for('main.countries'))

    flash('Something went wrong.')
    return redirect(url_for('crud.operations'))



@crud.route('/update_country', methods=['POST'])
@login_required
def update_country():
    # new_name, new_hdi_rank, name
    name = request.form.get('name')
    new_name = request.form.get('new_name')
    new_hdi_rank = request.form.get('new_hdi_rank')

    result = CountryRepository.update_country(new_name, new_hdi_rank, name)
    if result:
        return redirect(url_for('main.countries'))

    flash('Something went wrong.')
    return redirect(url_for('crud.operations'))

@crud.route('/insert_hdi', methods=['POST'])
@login_required
def insert_hdi():
    # country_id, hdi, life, education_e, education_m, gnhd, gni
    name = request.form.get('name')
    country_id = CountryRepository.fetch_country(name).id
    hdi = request.form.get('hdi')
    life = request.form.get('life')
    education_e = request.form.get('education_e')
    education_m = request.form.get('education_m')
    gnhd = request.form.get('gnhd')
    gni = request.form.get('gni')

    result = HdiRepository.insert_hdi(country_id, hdi, life, education_e, education_m, gnhd, gni)
    if result:
        return redirect(url_for('main.countries'))

    flash('Something went wrong.')
    return redirect(url_for('crud.operations'))


@crud.route('/update_hdi', methods=['POST'])
@login_required
def update_hdi():
    # country_id, hdi, life, education_e, education_m, gnhd, gni
    name = request.form.get('name')
    country_id = CountryRepository.fetch_country(name).id
    hdi = request.form.get('hdi')
    life = request.form.get('life')
    education_e = request.form.get('education_e')
    education_m = request.form.get('education_m')
    gnhd = request.form.get('gnhd')
    gni = request.form.get('gni')

    result = HdiRepository.update_hdi(country_id, hdi, life, education_e, education_m, gnhd, gni)
    if result:
        return redirect(url_for('main.countries'))

    flash('Something went wrong.')
    return redirect(url_for('crud.operations'))


@crud.route('/delete_hdi', methods=['POST'])
@login_required
def delete_hdi():
    # country_id
    name = request.form.get('name')
    country_id = CountryRepository.fetch_country(name).id

    result = HdiRepository.delete_hdi(country_id)
    if result:
        return redirect(url_for('main.countries'))

    flash('Something went wrong.')
    return redirect(url_for('crud.operations'))


@crud.route('/insert_historical', methods=['POST'])
@login_required
def insert_historical():
    name = request.form.get('name')
    country_id = CountryRepository.fetch_country(name).id
    year1990 = request.form.get('year1990')
    year2000 = request.form.get('year2000')
    year2010 = request.form.get('year2010')
    year2011 = request.form.get('year2011')
    year2012 = request.form.get('year2012')
    year2013 = request.form.get('year2013')

    result = HistoricalRepository.insert_historical(country_id, year1990, year2000, year2010, year2011, year2012, year2013)
    if result:
        return redirect(url_for('main.countries'))

    flash('Something went wrong.')
    return redirect(url_for('crud.operations'))


@crud.route('/update_historical', methods=['POST'])
@login_required
def update_historical():
    name = request.form.get('name')
    country_id = CountryRepository.fetch_country(name).id
    year1990 = request.form.get('year1990')
    year2000 = request.form.get('year2000')
    year2010 = request.form.get('year2010')
    year2011 = request.form.get('year2011')
    year2012 = request.form.get('year2012')
    year2013 = request.form.get('year2013')

    result = HistoricalRepository.update_historical(country_id, year1990, year2000, year2010, year2011, year2012, year2013)
    if result:
        return redirect(url_for('main.countries'))

    flash('Something went wrong.')
    return redirect(url_for('crud.operations'))


@crud.route('/delete_historical', methods=['POST'])
@login_required
def delete_historical():
    name = request.form.get('name')
    country_id = CountryRepository.fetch_country(name).id

    result = HistoricalRepository.delete_historical(country_id)
    if result:
        return redirect(url_for('main.countries'))

    flash('Something went wrong.')
    return redirect(url_for('crud.operations'))

Database Systems/term-project-itudb2140/interaktivt/routes/main.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user
from ..repository.Database import Database
from flask import request
from ..repository.UserRepository import UserRepository
from ..repository import CountryRepository
from ..repository import HdiRepository
from ..repository import HistoricalRepository
from flask import redirect
from flask import url_for
import datetime

main = Blueprint('main', __name__)


@main.route('/countries')
def countries():
    _countries = CountryRepository.fetch_country_all()
    return render_template('countries.html', countries=_countries)


@main.route('/countries_hdindex')
def countries_hdindex():
    all_country_indexes = HdiRepository.fetch_record_all()
    return render_template('hdindex.html', all_country_indexes=all_country_indexes)


@main.route('/country_historical_hdindex/<country_name>')
def country_historical_hdindex(country_name):
    historical_hdindex = HistoricalRepository.fetch_record(country_name)
    return render_template('historical_hdindex.html', historical_hdindex=historical_hdindex, country_name=country_name)


@main.route('/')
def index():
    day = datetime.datetime.now()
    return render_template('index.html', day=day.strftime("%A"))


@main.route('/profile')
@login_required
def profile():
    return render_template('profile.html', username=current_user.username)


# UPDATE USER INFORMATION GET
@main.route('/update')
@login_required
def update():
    return render_template('update.html')


# UPDATE USER INFORMATION POST
@main.route('/update', methods=['POST'])
@login_required
def update_post():
    email = current_user.email
    new_email = request.form.get('email')
    new_username = request.form.get('username')
    new_location = request.form.get('password')
    result = UserRepository.update_user(email=email, new_email=new_email, new_username=new_username,
                                        new_location=new_location)
    if result:
        return redirect(url_for('main.profile'))

    return redirect(url_for('main.update'))


@main.route('/delete', methods=['POST', 'GET'])
@login_required
def delete_user():
    if request.method == "POST":
        email = current_user.email
        confirmation_answer = request.form.get('confirmation')
        if confirmation_answer == 'YES':
            redirect(url_for('auth.logout'))
            result = UserRepository.delete_user(email=email)

        if result:
            print('user deletion successfull')

        return redirect(url_for('main.delete_user'))
    else:
        return render_template('delete.html')

Database Systems/term-project-itudb2140/interaktivt/templates/countries.html
{% extends "layout.html" %} {% block title %}GDI - Countries{% endblock %} {%
block content %}
<h1 class="title">Countries Human Development Indexes</h1>
<table class="table table-primary table-hover">
  <thead>
    <tr>
      <a
        href="{{ url_for('main.countries_hdindex') }}"
        style="float: left"
        class="btn btn-primary"
        ><span>&#8594; Countries Detailed Information</span>
      </a>
    </tr>
    <tr>
      <th scope="col"></th>
      <th scope="col">Country</th>
      <th scope="col">HDI Rank</th>
    </tr>
  </thead>
  <tbody>
    {% for country in countries %}
    <tr class="table-success">
      <th scope="row">{{loop.index}}</th>
      <td>{{ country.name }}</td>
      <td>{{ country.hdi_rank }}</td>
      <td>
        <a
          href="{{ url_for('main.country_historical_hdindex', country_name=country.name) }}"
          style="float: left"
          class="btn btn-primary"
          ><span>&#8594;</span>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<div style="text-align: center">
  <h3>Add your imaginary country!</h3>
  <div id="add_country_form"></div>
</div>
<script type="text/babel" src="./static/js/index.js"></script>
{% endblock %}

Database Systems/term-project-itudb2140/interaktivt/templates/crud.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
        {% endif %}
        {% endwith %}
        <h1>Countries Operations</h1>
        {# add country#}
        <h2>Add an imaginary country</h2>
        <form method="POST" action="/add_country">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Country name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="hdi_rank" placeholder="Hdi Rank">
                </div>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Add new country</button>
        </form>
        <br>
        {# delete country#}
        <h2>Delete country</h2>
        <form method="POST" action="/delete_country">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Country name" autofocus="">
                </div>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Delete country</button>
        </form>
        {# add country#}
{#        # new_name, new_hdi_rank, name#}
        <h2>Update an existing country</h2>
        <form method="POST" action="/update_country">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Country name" autofocus="">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="new_name" placeholder="Country new name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="new_hdi_rank" placeholder="New Hdi Rank">
                </div>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Update country</button>
        </form>


        <h1>HDI Operations</h1>

        <h2>Insert country HDI</h2>
        <form method="POST" action="/insert_hdi">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Country name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="hdi" placeholder="hdi">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="life" placeholder="Life expt.">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="education_e" placeholder="Education expt.">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="education_m" placeholder="Education Mean">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="gnhd" placeholder="GNHD">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="gni" placeholder="GNI">
                </div>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Add new country</button>
        </form>
        <br>

        <h2>Update country HDI</h2>
        <form method="POST" action="/update_hdi">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Country name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="hdi" placeholder="hdi">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="life" placeholder="Life expt.">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="education_e" placeholder="Education expt.">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="education_m" placeholder="Education Mean">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="gnhd" placeholder="GNHD">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="gni" placeholder="GNI">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Update country HDI</button>
        </form>

        <h2>Delete country HDI</h2>
        <form method="POST" action="/delete_hdi">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Country name" autofocus="">
                </div>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Delete country HDI</button>
        </form>



        <h1>Historical Operations</h1>
        <h2>Insert country historical</h2>
        <form method="POST" action="/insert_historical">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Country name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="year1990" placeholder="year1990">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="year2000" placeholder="year2000">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="year2010" placeholder="year2010">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="year2011" placeholder="year2011">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="year2012" placeholder="year2012">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="year2013" placeholder="year2013">
                </div>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Add new country historical</button>
        </form>
        <br>

        <h2>Update country historical</h2>
        <form method="POST" action="/update_historical">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Country name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="year1990" placeholder="year1990">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="year2000" placeholder="year2000">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="year2010" placeholder="year2010">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="year2011" placeholder="year2011">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="year2012" placeholder="year2012">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="year2013" placeholder="year2013">
                </div>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Update country historical</button>
        </form>

        <h2>Delete country historical</h2>
        <form method="POST" action="/delete_historical">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Country name" autofocus="">
                </div>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Delete country historical</button>
        </form>

</body>
</html>

Database Systems/term-project-itudb2140/interaktivt/templates/delete.html
{% extends "layout.html" %}

{% block content %}

    
<div class="column is-4 is-offset-4">
    <h3 class="title">Delete User</h3>
    <div class="box">

        <form method="POST" action="/delete">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="confirmation" placeholder="type 'YES'" autofocus="" required="required">
                </div>
            </div>
            <button class="button is-block is-danger is-large is-fullwidth">Delete User</button>
        </form>
    </div>
</div>

    
    
{% endblock %}

Database Systems/term-project-itudb2140/interaktivt/templates/hdindex.html
{% extends "layout.html" %} {% block title %}GDI - Countries{% endblock %} {%
block content %}
<h1 class="title">Countries Human Development Indexes</h1>
<table class="table table-primary table-hover">
  <thead>
    <tr>
      <a
        href="{{ url_for('main.countries') }}"
        style="float: left"
        class="btn btn-primary"
        ><span>&#8592; Countries HDI</span>
      </a>
    </tr>
    <tr>
      <th scope="col"></th>
      <th scope="col">Country Name</th>
      <th scope="col">HDI Rank</th>
      <th scope="col">Human Development Index (HDI)</th>
      <th scope="col">Life Expectancy at Birth</th>
      <th scope="col">Expected Years of Education</th>
      <th scope="col">Mean Years of Education</th>
      <th scope="col">Gross National Income (GNI) per Capita</th>
      <th scope="col">GNI per Capita Rank Minus HDI Rank</th>
    </tr>
  </thead>
  <tbody>
    {% for country_index in all_country_indexes %}
    <tr class="table-success">
      <th scope="row">{{loop.index}}</th>
      <td>{{ country_index.name }}</td>
      <td>{{ country_index.hdi_rank }}</td>
      <td>{{ country_index.hdi }}</td>
      <td>{{ country_index.life }}</td>
      <td>{{ country_index.education_e }}</td>
      <td>{{ country_index.education_m }}</td>
      <td>{{ country_index.gnhd }}</td>
      <td>{{ country_index.gni }}</td>
      <td>
        <a
          href="{{ url_for('main.country_historical_hdindex', country_name=country_index.name) }}"
          style="float: left"
          class="btn btn-primary"
          ><span>&#8594;</span>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

Database Systems/term-project-itudb2140/interaktivt/templates/historical_hdindex.html
{% extends "layout.html" %} {% block title %}GDI - Countries{% endblock %} {%
block content %}

<h1 class="title">{{ country_name }} Human Development Indexes</h1>
<table class="table table-primary table-hover">
  <thead>
    <tr>
      <a
        href="{{ url_for('main.countries') }}"
        style="float: left"
        class="btn btn-primary"
        ><span>&#8592; Back to Countries HDI</span>
      </a>
    </tr>
    <tr>
      <th scope="col">Country Name</th>
      <th scope="col">Year 1990</th>
      <th scope="col">Year 2000</th>
      <th scope="col">Year 2010</th>
      <th scope="col">Year 2011</th>
      <th scope="col">Year 2012</th>
      <th scope="col">Year 2013</th>
    </tr>
  </thead>
  <tbody>
    <tr class="table-success">
      <td>{{ country_name }}</td>
      <td>{{ historical_hdindex.year1990 }}</td>
      <td>{{ historical_hdindex.year2000 }}</td>
      <td>{{ historical_hdindex.year2010 }}</td>
      <td>{{ historical_hdindex.year2011 }}</td>
      <td>{{ historical_hdindex.year2012 }}</td>
      <td>{{ historical_hdindex.year2013 }}</td>
    </tr>
  </tbody>
</table>
{% endblock %}

Database Systems/term-project-itudb2140/interaktivt/templates/index.html
{% extends "layout.html" %}
{% block title %}GDI - Home{% endblock %}
{% block content %}

    <section class="hero">
      <div class="hero-body">
        <div class="container has-text-centered">
          <h1 class="title">HDI Explorer</h1>
          <p class="subtitle">Have a nice <strong>{{ day }}</strong>!!!</p>
        </div>
      </div>
    </section>

{% endblock %}

Database Systems/term-project-itudb2140/interaktivt/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Countries - {% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://unpkg.com/react@17/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom@17/umd/react-dom.development.js"></script>
    <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='countries.css') }}"/>
</head>
<body>
    <header>
      <nav class="navbar" aria-label="main navigation">

          <div class="navbar-end">
            <a href="{{ url_for('main.index') }}" class="navbar-item">
                Home
            </a>
            {% if current_user.is_authenticated %}
            <a href="{{ url_for('main.profile') }}" class="navbar-item">
                Profile
            </a>
            <a href="{{ url_for('main.update') }}" class="navbar-item">
                Info Update
            </a>
            <a href="{{ url_for('main.delete_user') }}" class="navbar-item">
                Delete User
            </a>
            {% endif %}
            {% if not current_user.is_authenticated %}
            <a href="{{ url_for('auth.login') }}" class="navbar-item">
                Login
            </a>
            <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                Sign Up
            </a>
            {% endif %}
            {% if current_user.is_authenticated %}
            <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                Logout
            </a>
            {% endif %}
            {% if current_user.is_authenticated %}
            <a href="{{ url_for('crud.operations') }}" class="navbar-item">
                CRUD OPS
            </a>
            <a href="{{ url_for('main.countries') }}" class="navbar-item">
                Countries
            </a>
            {% endif %}

        </div>


      </nav>
    </header>

    <main>
      <section class="section">
        <div class="content">
          {% block content %}{% endblock %}
        </div>
      </section>
    </main>

    <footer class="footer">
      <div class="content">
        <small>&copy; 2021, Yasin A. Yokus</small>
      </div>
    </footer>
</body>
</html>

Database Systems/term-project-itudb2140/interaktivt/templates/login.html
{% extends "layout.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">

        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
        {% endif %}
        {% endwith %}

        <form method="POST" action="/login">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Your Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Your Password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox" name="remember">
                    Remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}

Database Systems/term-project-itudb2140/interaktivt/templates/profile.html
{% extends "layout.html" %}

{% block content %}
<h1 class="title">
  Welcome, {{ username }}!
</h1>
{% endblock %}